#!/bin/bash

sudo apt-get -y install whois 
temp_pwd=$(mkpasswd -m sha-512 'vtr512')


sudo useradd -m -s /bin/bash deploy
sudo passwd -l deploy

echo "### set deploy to sudoers"
if sudo grep "deploy" /etc/sudoers -q 
then
echo deploy params already set to sudoers!
else
echo doing...
sudo su -c "echo '%deploy ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
echo done.
fi

sudo useradd -m -p $temp_pwd -s /bin/bash user1
sudo useradd -m -p $temp_pwd -s /bin/bash user2


