#!/bin/bash
# FIRST PREPARE THE VM FIRST
# sudo apt-get install -y dkms build-essential linux-headers-generic linux-headers-$(uname -r)
# sudo mount /dev/cdrom /media/cdrom
# sudo /media/cdrom/VBoxLinuxAdditions.run
# sudo apt-get -y install wget unzip
# sudo passwd

./begin
./add_users

echo "then execute rvm_installer as root"
echo "then execute a personal_user_custom to each user" # root, admin_user, deploy

# dnsserver_installer # as root
# mailserver_installer # as root
# services_monit # as root
